---
- name: Deploy Mysql/Httpd/Wordpress
  hosts:   all 
  become: true
  roles:
    - { role:  sysdev.mysql, tags: mysql }
    - { role:  sysdev.httpd, tags: web }
    - { role:  sysdev.wordpress, tags: wordpress }

